expert_data:
  shuffle: True
  train_fraction: !!float 0.7
  traj_limitation: 50
  batch_size: 4000

train:
  general:
    training_epochs: 20000
    seed: 2020
  generator:
    gamma: 0.995
    tau: 0.97
    clip_ratio: 0.2
    optim_step: 10
    mini_batch_size: 500
    sample_batch_size: 4000
  discriminator:
    optim_step: 1
    ent_coeff: 0.5

policy:
  dim_state: 155
  dim_action: 6
  dim_hidden: 128
  activation: LeakyReLU
  dim_disc_action: 0
  action_log_std: 0.0
  disc_action_sections: !!python/tuple [0]
  use_multivariate_distribution: False
  learning_rate: !!float 3e-4


value:
  dim_state: 155
  dim_hidden: 128
  activation: LeakyReLU
  optim_value_iter: 3
  learning_rate: !!float 3e-3
  l2_reg: !!float 1e-3


discriminator:
  dim_state: 155
  dim_action: 6
  dim_hidden: 128
  activation: LeakyReLU
  learning_rate: !!float 1e-4
